variables:
  LIBNODE_NODE_VERSION: 'v15.10.0'

jobs:
  - job: build
    timeoutInMinutes: 120
    strategy:
      matrix:
        linux:
          imageName: 'ubuntu-18.04'
        mac:
          imageName: 'macOS-10.15'
        win_x64:
          imageName: 'windows-2019'
        win_x86:
          LIBNODE_X86: '1'
          imageName: 'windows-2019'
        linux_nointl:
          LIBNODE_CONFIG_FLAGS: '--without-intl'
          LIBNODE_ZIP_SUFFIX: '-nointl'
          imageName: 'ubuntu-18.04'
        mac_nointl:
          LIBNODE_CONFIG_FLAGS: '--without-intl'
          LIBNODE_ZIP_SUFFIX: '-nointl'
          imageName: 'macOS-10.15'
        win_x64_nointl:
          LIBNODE_CONFIG_FLAGS: '--without-intl'
          LIBNODE_ZIP_SUFFIX: '-nointl'
          imageName: 'windows-2019'
        win_x86_nointl:
          LIBNODE_CONFIG_FLAGS: '--without-intl'
          LIBNODE_ZIP_SUFFIX: '-nointl'
          LIBNODE_X86: '1'
          imageName: 'windows-2019'
    pool:
      vmImage: $(imageName)

    steps:
        
    - task: UsePythonVersion@0

    - script: |
        choco install -y nasm
      condition: eq( variables['Agent.OS'], 'Windows_NT' )
      displayName: 'Install nasm on Windows'


    - script: HOMEBREW_NO_AUTO_UPDATE=1 brew install ninja
      condition: eq( variables['Agent.OS'], 'Darwin' )
      displayName: 'Install Ninja on macOS'

    - script: sudo apt-get install -y ninja-build
      condition: eq( variables['Agent.OS'], 'Linux' )
      displayName: 'Install Ninja on Linux'

    - script: |
        choco install -y patch
      condition: eq( variables['Agent.OS'], 'Windows_NT' )
      displayName: 'Install GNU patch on Windows'

    - bash: python -m scripts.download
      displayName: 'Download source code of Node.js'

    - bash: python -m scripts.patch
      displayName: 'Patch source code of Node.js'

    - bash: python -m scripts.build
      displayName: 'Build'

    - bash: python -m scripts.headers
      displayName: 'Copy Headers'

    - script: |
        SET PATH=%PATH%;$(Build.SourcesDirectory)\ninja
        pushd "C:\Program Files (x86)\Microsoft Visual Studio\Installer\"
        for /f "delims=" %%x in ('.\vswhere.exe -latest -property InstallationPath') do set VSPATH=%%x
        popd
        call "%VSPATH%\VC\Auxiliary\Build\vcvars64.bat"
        python -m scripts.postproc
      condition: eq( variables['Agent.OS'], 'Windows_NT' )
      displayName: 'Postprocess'

    - bash: python -m scripts.postproc
      condition: ne( variables['Agent.OS'], 'Windows_NT' )
      displayName: 'Postprocess'

    - bash: |
        output=$(python -m scripts.archive)
        echo "##vso[task.setvariable variable=zip_file;]$output"
      displayName: 'Archive'
    
    - task: PublishBuildArtifacts@1
      inputs:
        artifactName: $(zip_file)
        pathtoPublish: $(zip_file)

    - bash: python -m scripts.test
      displayName: 'Test'
        
  - job: gh_release
    dependsOn: build
    imageName: 'ubuntu-18.04'
    steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        downloadType: 'specific'
        downloadPath: $(Build.ArtifactStagingDirectory)
    - bash: |
        echo '```' > release_notes.md
        sha1sum --binary *.zip >> release_notes.md
        echo '```' >> release_notes.md        
      workingDirectory: $(Build.ArtifactStagingDirectory)
    - task: GitHubRelease@0
      inputs:
        gitHubConnection: 'GitHub connection 1'
        repositoryName: patr0nus/libnode
        action: 'create'
        target: '$(Build.SourceVersion)'
        tagSource: 'manual'
        tag: 'libnode-$(LIBNODE_NODE_VERSION)'
        assets: '$(Build.ArtifactStagingDirectory)/*.zip'
        releaseNotesSource: 'file'
        releaseNotes: 'release_notes.md'
        isDraft: false
        addChangeLog: false
